/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSuperadminRouteImport } from './routes/admin/_superadmin'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminTryoutsIndexRouteImport } from './routes/admin/tryouts/index'
import { Route as AdminQuestionsIndexRouteImport } from './routes/admin/questions/index'
import { Route as AdminPassingGradesIndexRouteImport } from './routes/admin/passing-grades/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminClassesIndexRouteImport } from './routes/admin/classes/index'
import { Route as AuthenticatedTryoutIndexRouteImport } from './routes/_authenticated/tryout/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AdminQuestionsCreateRouteImport } from './routes/admin/questions/create'
import { Route as AdminQuestionsQuestionIdRouteImport } from './routes/admin/questions/$questionId'
import { Route as AdminPassingGradesUniversityIdRouteImport } from './routes/admin/passing-grades/$universityId'
import { Route as AuthenticatedTryoutTryoutIdRouteImport } from './routes/_authenticated/tryout/$tryoutId'
import { Route as AdminTryoutsTryoutIdIndexRouteImport } from './routes/admin/tryouts/$tryoutId/index'
import { Route as AdminClassesSubjectIdIndexRouteImport } from './routes/admin/classes/$subjectId/index'
import { Route as AdminSuperadminUsersIndexRouteImport } from './routes/admin/_superadmin/users/index'
import { Route as AdminSuperadminReferralsIndexRouteImport } from './routes/admin/_superadmin/referrals/index'
import { Route as AdminSuperadminProductsIndexRouteImport } from './routes/admin/_superadmin/products/index'
import { Route as AuthenticatedClassesSubjectIdIndexRouteImport } from './routes/_authenticated/classes/$subjectId/index'
import { Route as AdminClassesSubjectIdContentIdRouteImport } from './routes/admin/classes/$subjectId/$contentId'
import { Route as AdminSuperadminUsersUserIdRouteImport } from './routes/admin/_superadmin/users/$userId'
import { Route as AdminSuperadminReferralsCodeIdRouteImport } from './routes/admin/_superadmin/referrals/$codeId'
import { Route as AdminSuperadminProductsCreateRouteImport } from './routes/admin/_superadmin/products/create'
import { Route as AdminSuperadminProductsProductIdRouteImport } from './routes/admin/_superadmin/products/$productId'
import { Route as AuthenticatedTryoutResultsAttemptIdRouteImport } from './routes/_authenticated/tryout/results.$attemptId'
import { Route as AuthenticatedClassesSubjectIdContentIdRouteImport } from './routes/_authenticated/classes/$subjectId/$contentId'
import { Route as AdminClassesSubjectIdContentIdVideoRouteImport } from './routes/admin/classes/$subjectId/$contentId.video'
import { Route as AdminClassesSubjectIdContentIdNotesRouteImport } from './routes/admin/classes/$subjectId/$contentId.notes'
import { Route as AdminClassesSubjectIdContentIdLatihanSoalRouteImport } from './routes/admin/classes/$subjectId/$contentId.latihan-soal'
import { Route as AuthenticatedTryoutReviewAttemptIdSubtestIdRouteImport } from './routes/_authenticated/tryout/review.$attemptId.$subtestId'
import { Route as AuthenticatedClassesSubjectIdContentIdVideoRouteImport } from './routes/_authenticated/classes/$subjectId/$contentId.video'
import { Route as AuthenticatedClassesSubjectIdContentIdNotesRouteImport } from './routes/_authenticated/classes/$subjectId/$contentId.notes'
import { Route as AuthenticatedClassesSubjectIdContentIdLatihanSoalRouteImport } from './routes/_authenticated/classes/$subjectId/$contentId.latihan-soal'
import { Route as AdminTryoutsTryoutIdSubtestsSubtestIdIndexRouteImport } from './routes/admin/tryouts/$tryoutId/subtests/$subtestId.index'
import { Route as AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRouteImport } from './routes/admin/tryouts/$tryoutId/subtests/$subtestId.questions.new'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuperadminRoute = AdminSuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTryoutsIndexRoute = AdminTryoutsIndexRouteImport.update({
  id: '/tryouts/',
  path: '/tryouts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsIndexRoute = AdminQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPassingGradesIndexRoute = AdminPassingGradesIndexRouteImport.update({
  id: '/passing-grades/',
  path: '/passing-grades/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesIndexRoute = AdminClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTryoutIndexRoute =
  AuthenticatedTryoutIndexRouteImport.update({
    id: '/tryout/',
    path: '/tryout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminQuestionsCreateRoute = AdminQuestionsCreateRouteImport.update({
  id: '/questions/create',
  path: '/questions/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsQuestionIdRoute =
  AdminQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPassingGradesUniversityIdRoute =
  AdminPassingGradesUniversityIdRouteImport.update({
    id: '/passing-grades/$universityId',
    path: '/passing-grades/$universityId',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthenticatedTryoutTryoutIdRoute =
  AuthenticatedTryoutTryoutIdRouteImport.update({
    id: '/tryout/$tryoutId',
    path: '/tryout/$tryoutId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminTryoutsTryoutIdIndexRoute =
  AdminTryoutsTryoutIdIndexRouteImport.update({
    id: '/tryouts/$tryoutId/',
    path: '/tryouts/$tryoutId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClassesSubjectIdIndexRoute =
  AdminClassesSubjectIdIndexRouteImport.update({
    id: '/classes/$subjectId/',
    path: '/classes/$subjectId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSuperadminUsersIndexRoute =
  AdminSuperadminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AdminSuperadminReferralsIndexRoute =
  AdminSuperadminReferralsIndexRouteImport.update({
    id: '/referrals/',
    path: '/referrals/',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AdminSuperadminProductsIndexRoute =
  AdminSuperadminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AuthenticatedClassesSubjectIdIndexRoute =
  AuthenticatedClassesSubjectIdIndexRouteImport.update({
    id: '/classes/$subjectId/',
    path: '/classes/$subjectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminClassesSubjectIdContentIdRoute =
  AdminClassesSubjectIdContentIdRouteImport.update({
    id: '/classes/$subjectId/$contentId',
    path: '/classes/$subjectId/$contentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSuperadminUsersUserIdRoute =
  AdminSuperadminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AdminSuperadminReferralsCodeIdRoute =
  AdminSuperadminReferralsCodeIdRouteImport.update({
    id: '/referrals/$codeId',
    path: '/referrals/$codeId',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AdminSuperadminProductsCreateRoute =
  AdminSuperadminProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AdminSuperadminProductsProductIdRoute =
  AdminSuperadminProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AdminSuperadminRoute,
  } as any)
const AuthenticatedTryoutResultsAttemptIdRoute =
  AuthenticatedTryoutResultsAttemptIdRouteImport.update({
    id: '/tryout/results/$attemptId',
    path: '/tryout/results/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesSubjectIdContentIdRoute =
  AuthenticatedClassesSubjectIdContentIdRouteImport.update({
    id: '/classes/$subjectId/$contentId',
    path: '/classes/$subjectId/$contentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminClassesSubjectIdContentIdVideoRoute =
  AdminClassesSubjectIdContentIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AdminClassesSubjectIdContentIdRoute,
  } as any)
const AdminClassesSubjectIdContentIdNotesRoute =
  AdminClassesSubjectIdContentIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AdminClassesSubjectIdContentIdRoute,
  } as any)
const AdminClassesSubjectIdContentIdLatihanSoalRoute =
  AdminClassesSubjectIdContentIdLatihanSoalRouteImport.update({
    id: '/latihan-soal',
    path: '/latihan-soal',
    getParentRoute: () => AdminClassesSubjectIdContentIdRoute,
  } as any)
const AuthenticatedTryoutReviewAttemptIdSubtestIdRoute =
  AuthenticatedTryoutReviewAttemptIdSubtestIdRouteImport.update({
    id: '/tryout/review/$attemptId/$subtestId',
    path: '/tryout/review/$attemptId/$subtestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesSubjectIdContentIdVideoRoute =
  AuthenticatedClassesSubjectIdContentIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedClassesSubjectIdContentIdRoute,
  } as any)
const AuthenticatedClassesSubjectIdContentIdNotesRoute =
  AuthenticatedClassesSubjectIdContentIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedClassesSubjectIdContentIdRoute,
  } as any)
const AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute =
  AuthenticatedClassesSubjectIdContentIdLatihanSoalRouteImport.update({
    id: '/latihan-soal',
    path: '/latihan-soal',
    getParentRoute: () => AuthenticatedClassesSubjectIdContentIdRoute,
  } as any)
const AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute =
  AdminTryoutsTryoutIdSubtestsSubtestIdIndexRouteImport.update({
    id: '/tryouts/$tryoutId/subtests/$subtestId/',
    path: '/tryouts/$tryoutId/subtests/$subtestId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute =
  AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRouteImport.update({
    id: '/tryouts/$tryoutId/subtests/$subtestId/questions/new',
    path: '/tryouts/$tryoutId/subtests/$subtestId/questions/new',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminSuperadminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/admin/': typeof AdminIndexRoute
  '/tryout/$tryoutId': typeof AuthenticatedTryoutTryoutIdRoute
  '/admin/passing-grades/$universityId': typeof AdminPassingGradesUniversityIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/tryout/': typeof AuthenticatedTryoutIndexRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/passing-grades/': typeof AdminPassingGradesIndexRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/tryouts/': typeof AdminTryoutsIndexRoute
  '/classes/$subjectId/$contentId': typeof AuthenticatedClassesSubjectIdContentIdRouteWithChildren
  '/tryout/results/$attemptId': typeof AuthenticatedTryoutResultsAttemptIdRoute
  '/admin/products/$productId': typeof AdminSuperadminProductsProductIdRoute
  '/admin/products/create': typeof AdminSuperadminProductsCreateRoute
  '/admin/referrals/$codeId': typeof AdminSuperadminReferralsCodeIdRoute
  '/admin/users/$userId': typeof AdminSuperadminUsersUserIdRoute
  '/admin/classes/$subjectId/$contentId': typeof AdminClassesSubjectIdContentIdRouteWithChildren
  '/classes/$subjectId/': typeof AuthenticatedClassesSubjectIdIndexRoute
  '/admin/products/': typeof AdminSuperadminProductsIndexRoute
  '/admin/referrals/': typeof AdminSuperadminReferralsIndexRoute
  '/admin/users/': typeof AdminSuperadminUsersIndexRoute
  '/admin/classes/$subjectId/': typeof AdminClassesSubjectIdIndexRoute
  '/admin/tryouts/$tryoutId/': typeof AdminTryoutsTryoutIdIndexRoute
  '/classes/$subjectId/$contentId/latihan-soal': typeof AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute
  '/classes/$subjectId/$contentId/notes': typeof AuthenticatedClassesSubjectIdContentIdNotesRoute
  '/classes/$subjectId/$contentId/video': typeof AuthenticatedClassesSubjectIdContentIdVideoRoute
  '/tryout/review/$attemptId/$subtestId': typeof AuthenticatedTryoutReviewAttemptIdSubtestIdRoute
  '/admin/classes/$subjectId/$contentId/latihan-soal': typeof AdminClassesSubjectIdContentIdLatihanSoalRoute
  '/admin/classes/$subjectId/$contentId/notes': typeof AdminClassesSubjectIdContentIdNotesRoute
  '/admin/classes/$subjectId/$contentId/video': typeof AdminClassesSubjectIdContentIdVideoRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId/': typeof AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new': typeof AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/admin': typeof AdminIndexRoute
  '/tryout/$tryoutId': typeof AuthenticatedTryoutTryoutIdRoute
  '/admin/passing-grades/$universityId': typeof AdminPassingGradesUniversityIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/tryout': typeof AuthenticatedTryoutIndexRoute
  '/admin/classes': typeof AdminClassesIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/passing-grades': typeof AdminPassingGradesIndexRoute
  '/admin/questions': typeof AdminQuestionsIndexRoute
  '/admin/tryouts': typeof AdminTryoutsIndexRoute
  '/classes/$subjectId/$contentId': typeof AuthenticatedClassesSubjectIdContentIdRouteWithChildren
  '/tryout/results/$attemptId': typeof AuthenticatedTryoutResultsAttemptIdRoute
  '/admin/products/$productId': typeof AdminSuperadminProductsProductIdRoute
  '/admin/products/create': typeof AdminSuperadminProductsCreateRoute
  '/admin/referrals/$codeId': typeof AdminSuperadminReferralsCodeIdRoute
  '/admin/users/$userId': typeof AdminSuperadminUsersUserIdRoute
  '/admin/classes/$subjectId/$contentId': typeof AdminClassesSubjectIdContentIdRouteWithChildren
  '/classes/$subjectId': typeof AuthenticatedClassesSubjectIdIndexRoute
  '/admin/products': typeof AdminSuperadminProductsIndexRoute
  '/admin/referrals': typeof AdminSuperadminReferralsIndexRoute
  '/admin/users': typeof AdminSuperadminUsersIndexRoute
  '/admin/classes/$subjectId': typeof AdminClassesSubjectIdIndexRoute
  '/admin/tryouts/$tryoutId': typeof AdminTryoutsTryoutIdIndexRoute
  '/classes/$subjectId/$contentId/latihan-soal': typeof AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute
  '/classes/$subjectId/$contentId/notes': typeof AuthenticatedClassesSubjectIdContentIdNotesRoute
  '/classes/$subjectId/$contentId/video': typeof AuthenticatedClassesSubjectIdContentIdVideoRoute
  '/tryout/review/$attemptId/$subtestId': typeof AuthenticatedTryoutReviewAttemptIdSubtestIdRoute
  '/admin/classes/$subjectId/$contentId/latihan-soal': typeof AdminClassesSubjectIdContentIdLatihanSoalRoute
  '/admin/classes/$subjectId/$contentId/notes': typeof AdminClassesSubjectIdContentIdNotesRoute
  '/admin/classes/$subjectId/$contentId/video': typeof AdminClassesSubjectIdContentIdVideoRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId': typeof AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new': typeof AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/admin/_superadmin': typeof AdminSuperadminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/tryout/$tryoutId': typeof AuthenticatedTryoutTryoutIdRoute
  '/admin/passing-grades/$universityId': typeof AdminPassingGradesUniversityIdRoute
  '/admin/questions/$questionId': typeof AdminQuestionsQuestionIdRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/tryout/': typeof AuthenticatedTryoutIndexRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/passing-grades/': typeof AdminPassingGradesIndexRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/tryouts/': typeof AdminTryoutsIndexRoute
  '/_authenticated/classes/$subjectId/$contentId': typeof AuthenticatedClassesSubjectIdContentIdRouteWithChildren
  '/_authenticated/tryout/results/$attemptId': typeof AuthenticatedTryoutResultsAttemptIdRoute
  '/admin/_superadmin/products/$productId': typeof AdminSuperadminProductsProductIdRoute
  '/admin/_superadmin/products/create': typeof AdminSuperadminProductsCreateRoute
  '/admin/_superadmin/referrals/$codeId': typeof AdminSuperadminReferralsCodeIdRoute
  '/admin/_superadmin/users/$userId': typeof AdminSuperadminUsersUserIdRoute
  '/admin/classes/$subjectId/$contentId': typeof AdminClassesSubjectIdContentIdRouteWithChildren
  '/_authenticated/classes/$subjectId/': typeof AuthenticatedClassesSubjectIdIndexRoute
  '/admin/_superadmin/products/': typeof AdminSuperadminProductsIndexRoute
  '/admin/_superadmin/referrals/': typeof AdminSuperadminReferralsIndexRoute
  '/admin/_superadmin/users/': typeof AdminSuperadminUsersIndexRoute
  '/admin/classes/$subjectId/': typeof AdminClassesSubjectIdIndexRoute
  '/admin/tryouts/$tryoutId/': typeof AdminTryoutsTryoutIdIndexRoute
  '/_authenticated/classes/$subjectId/$contentId/latihan-soal': typeof AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute
  '/_authenticated/classes/$subjectId/$contentId/notes': typeof AuthenticatedClassesSubjectIdContentIdNotesRoute
  '/_authenticated/classes/$subjectId/$contentId/video': typeof AuthenticatedClassesSubjectIdContentIdVideoRoute
  '/_authenticated/tryout/review/$attemptId/$subtestId': typeof AuthenticatedTryoutReviewAttemptIdSubtestIdRoute
  '/admin/classes/$subjectId/$contentId/latihan-soal': typeof AdminClassesSubjectIdContentIdLatihanSoalRoute
  '/admin/classes/$subjectId/$contentId/notes': typeof AdminClassesSubjectIdContentIdNotesRoute
  '/admin/classes/$subjectId/$contentId/video': typeof AdminClassesSubjectIdContentIdVideoRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId/': typeof AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute
  '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new': typeof AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/premium'
    | '/admin/'
    | '/tryout/$tryoutId'
    | '/admin/passing-grades/$universityId'
    | '/admin/questions/$questionId'
    | '/admin/questions/create'
    | '/classes/'
    | '/dashboard/'
    | '/tryout/'
    | '/admin/classes/'
    | '/admin/dashboard/'
    | '/admin/passing-grades/'
    | '/admin/questions/'
    | '/admin/tryouts/'
    | '/classes/$subjectId/$contentId'
    | '/tryout/results/$attemptId'
    | '/admin/products/$productId'
    | '/admin/products/create'
    | '/admin/referrals/$codeId'
    | '/admin/users/$userId'
    | '/admin/classes/$subjectId/$contentId'
    | '/classes/$subjectId/'
    | '/admin/products/'
    | '/admin/referrals/'
    | '/admin/users/'
    | '/admin/classes/$subjectId/'
    | '/admin/tryouts/$tryoutId/'
    | '/classes/$subjectId/$contentId/latihan-soal'
    | '/classes/$subjectId/$contentId/notes'
    | '/classes/$subjectId/$contentId/video'
    | '/tryout/review/$attemptId/$subtestId'
    | '/admin/classes/$subjectId/$contentId/latihan-soal'
    | '/admin/classes/$subjectId/$contentId/notes'
    | '/admin/classes/$subjectId/$contentId/video'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId/'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/premium'
    | '/admin'
    | '/tryout/$tryoutId'
    | '/admin/passing-grades/$universityId'
    | '/admin/questions/$questionId'
    | '/admin/questions/create'
    | '/classes'
    | '/dashboard'
    | '/tryout'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/passing-grades'
    | '/admin/questions'
    | '/admin/tryouts'
    | '/classes/$subjectId/$contentId'
    | '/tryout/results/$attemptId'
    | '/admin/products/$productId'
    | '/admin/products/create'
    | '/admin/referrals/$codeId'
    | '/admin/users/$userId'
    | '/admin/classes/$subjectId/$contentId'
    | '/classes/$subjectId'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/users'
    | '/admin/classes/$subjectId'
    | '/admin/tryouts/$tryoutId'
    | '/classes/$subjectId/$contentId/latihan-soal'
    | '/classes/$subjectId/$contentId/notes'
    | '/classes/$subjectId/$contentId/video'
    | '/tryout/review/$attemptId/$subtestId'
    | '/admin/classes/$subjectId/$contentId/latihan-soal'
    | '/admin/classes/$subjectId/$contentId/notes'
    | '/admin/classes/$subjectId/$contentId/video'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_authenticated/premium'
    | '/admin/_superadmin'
    | '/admin/'
    | '/_authenticated/tryout/$tryoutId'
    | '/admin/passing-grades/$universityId'
    | '/admin/questions/$questionId'
    | '/admin/questions/create'
    | '/_authenticated/classes/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/tryout/'
    | '/admin/classes/'
    | '/admin/dashboard/'
    | '/admin/passing-grades/'
    | '/admin/questions/'
    | '/admin/tryouts/'
    | '/_authenticated/classes/$subjectId/$contentId'
    | '/_authenticated/tryout/results/$attemptId'
    | '/admin/_superadmin/products/$productId'
    | '/admin/_superadmin/products/create'
    | '/admin/_superadmin/referrals/$codeId'
    | '/admin/_superadmin/users/$userId'
    | '/admin/classes/$subjectId/$contentId'
    | '/_authenticated/classes/$subjectId/'
    | '/admin/_superadmin/products/'
    | '/admin/_superadmin/referrals/'
    | '/admin/_superadmin/users/'
    | '/admin/classes/$subjectId/'
    | '/admin/tryouts/$tryoutId/'
    | '/_authenticated/classes/$subjectId/$contentId/latihan-soal'
    | '/_authenticated/classes/$subjectId/$contentId/notes'
    | '/_authenticated/classes/$subjectId/$contentId/video'
    | '/_authenticated/tryout/review/$attemptId/$subtestId'
    | '/admin/classes/$subjectId/$contentId/latihan-soal'
    | '/admin/classes/$subjectId/$contentId/notes'
    | '/admin/classes/$subjectId/$contentId/video'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId/'
    | '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_superadmin': {
      id: '/admin/_superadmin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminSuperadminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/tryouts/': {
      id: '/admin/tryouts/'
      path: '/tryouts'
      fullPath: '/admin/tryouts/'
      preLoaderRoute: typeof AdminTryoutsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/': {
      id: '/admin/questions/'
      path: '/questions'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AdminQuestionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/passing-grades/': {
      id: '/admin/passing-grades/'
      path: '/passing-grades'
      fullPath: '/admin/passing-grades/'
      preLoaderRoute: typeof AdminPassingGradesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes/': {
      id: '/admin/classes/'
      path: '/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AdminClassesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tryout/': {
      id: '/_authenticated/tryout/'
      path: '/tryout'
      fullPath: '/tryout/'
      preLoaderRoute: typeof AuthenticatedTryoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/questions/create': {
      id: '/admin/questions/create'
      path: '/questions/create'
      fullPath: '/admin/questions/create'
      preLoaderRoute: typeof AdminQuestionsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/$questionId': {
      id: '/admin/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AdminQuestionsQuestionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/passing-grades/$universityId': {
      id: '/admin/passing-grades/$universityId'
      path: '/passing-grades/$universityId'
      fullPath: '/admin/passing-grades/$universityId'
      preLoaderRoute: typeof AdminPassingGradesUniversityIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tryout/$tryoutId': {
      id: '/_authenticated/tryout/$tryoutId'
      path: '/tryout/$tryoutId'
      fullPath: '/tryout/$tryoutId'
      preLoaderRoute: typeof AuthenticatedTryoutTryoutIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/tryouts/$tryoutId/': {
      id: '/admin/tryouts/$tryoutId/'
      path: '/tryouts/$tryoutId'
      fullPath: '/admin/tryouts/$tryoutId/'
      preLoaderRoute: typeof AdminTryoutsTryoutIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes/$subjectId/': {
      id: '/admin/classes/$subjectId/'
      path: '/classes/$subjectId'
      fullPath: '/admin/classes/$subjectId/'
      preLoaderRoute: typeof AdminClassesSubjectIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_superadmin/users/': {
      id: '/admin/_superadmin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminSuperadminUsersIndexRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/admin/_superadmin/referrals/': {
      id: '/admin/_superadmin/referrals/'
      path: '/referrals'
      fullPath: '/admin/referrals/'
      preLoaderRoute: typeof AdminSuperadminReferralsIndexRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/admin/_superadmin/products/': {
      id: '/admin/_superadmin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminSuperadminProductsIndexRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/_authenticated/classes/$subjectId/': {
      id: '/_authenticated/classes/$subjectId/'
      path: '/classes/$subjectId'
      fullPath: '/classes/$subjectId/'
      preLoaderRoute: typeof AuthenticatedClassesSubjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/classes/$subjectId/$contentId': {
      id: '/admin/classes/$subjectId/$contentId'
      path: '/classes/$subjectId/$contentId'
      fullPath: '/admin/classes/$subjectId/$contentId'
      preLoaderRoute: typeof AdminClassesSubjectIdContentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_superadmin/users/$userId': {
      id: '/admin/_superadmin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminSuperadminUsersUserIdRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/admin/_superadmin/referrals/$codeId': {
      id: '/admin/_superadmin/referrals/$codeId'
      path: '/referrals/$codeId'
      fullPath: '/admin/referrals/$codeId'
      preLoaderRoute: typeof AdminSuperadminReferralsCodeIdRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/admin/_superadmin/products/create': {
      id: '/admin/_superadmin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminSuperadminProductsCreateRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/admin/_superadmin/products/$productId': {
      id: '/admin/_superadmin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminSuperadminProductsProductIdRouteImport
      parentRoute: typeof AdminSuperadminRoute
    }
    '/_authenticated/tryout/results/$attemptId': {
      id: '/_authenticated/tryout/results/$attemptId'
      path: '/tryout/results/$attemptId'
      fullPath: '/tryout/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedTryoutResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$subjectId/$contentId': {
      id: '/_authenticated/classes/$subjectId/$contentId'
      path: '/classes/$subjectId/$contentId'
      fullPath: '/classes/$subjectId/$contentId'
      preLoaderRoute: typeof AuthenticatedClassesSubjectIdContentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/classes/$subjectId/$contentId/video': {
      id: '/admin/classes/$subjectId/$contentId/video'
      path: '/video'
      fullPath: '/admin/classes/$subjectId/$contentId/video'
      preLoaderRoute: typeof AdminClassesSubjectIdContentIdVideoRouteImport
      parentRoute: typeof AdminClassesSubjectIdContentIdRoute
    }
    '/admin/classes/$subjectId/$contentId/notes': {
      id: '/admin/classes/$subjectId/$contentId/notes'
      path: '/notes'
      fullPath: '/admin/classes/$subjectId/$contentId/notes'
      preLoaderRoute: typeof AdminClassesSubjectIdContentIdNotesRouteImport
      parentRoute: typeof AdminClassesSubjectIdContentIdRoute
    }
    '/admin/classes/$subjectId/$contentId/latihan-soal': {
      id: '/admin/classes/$subjectId/$contentId/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/admin/classes/$subjectId/$contentId/latihan-soal'
      preLoaderRoute: typeof AdminClassesSubjectIdContentIdLatihanSoalRouteImport
      parentRoute: typeof AdminClassesSubjectIdContentIdRoute
    }
    '/_authenticated/tryout/review/$attemptId/$subtestId': {
      id: '/_authenticated/tryout/review/$attemptId/$subtestId'
      path: '/tryout/review/$attemptId/$subtestId'
      fullPath: '/tryout/review/$attemptId/$subtestId'
      preLoaderRoute: typeof AuthenticatedTryoutReviewAttemptIdSubtestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$subjectId/$contentId/video': {
      id: '/_authenticated/classes/$subjectId/$contentId/video'
      path: '/video'
      fullPath: '/classes/$subjectId/$contentId/video'
      preLoaderRoute: typeof AuthenticatedClassesSubjectIdContentIdVideoRouteImport
      parentRoute: typeof AuthenticatedClassesSubjectIdContentIdRoute
    }
    '/_authenticated/classes/$subjectId/$contentId/notes': {
      id: '/_authenticated/classes/$subjectId/$contentId/notes'
      path: '/notes'
      fullPath: '/classes/$subjectId/$contentId/notes'
      preLoaderRoute: typeof AuthenticatedClassesSubjectIdContentIdNotesRouteImport
      parentRoute: typeof AuthenticatedClassesSubjectIdContentIdRoute
    }
    '/_authenticated/classes/$subjectId/$contentId/latihan-soal': {
      id: '/_authenticated/classes/$subjectId/$contentId/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/classes/$subjectId/$contentId/latihan-soal'
      preLoaderRoute: typeof AuthenticatedClassesSubjectIdContentIdLatihanSoalRouteImport
      parentRoute: typeof AuthenticatedClassesSubjectIdContentIdRoute
    }
    '/admin/tryouts/$tryoutId/subtests/$subtestId/': {
      id: '/admin/tryouts/$tryoutId/subtests/$subtestId/'
      path: '/tryouts/$tryoutId/subtests/$subtestId'
      fullPath: '/admin/tryouts/$tryoutId/subtests/$subtestId/'
      preLoaderRoute: typeof AdminTryoutsTryoutIdSubtestsSubtestIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new': {
      id: '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new'
      path: '/tryouts/$tryoutId/subtests/$subtestId/questions/new'
      fullPath: '/admin/tryouts/$tryoutId/subtests/$subtestId/questions/new'
      preLoaderRoute: typeof AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedClassesSubjectIdContentIdRouteChildren {
  AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute: typeof AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute
  AuthenticatedClassesSubjectIdContentIdNotesRoute: typeof AuthenticatedClassesSubjectIdContentIdNotesRoute
  AuthenticatedClassesSubjectIdContentIdVideoRoute: typeof AuthenticatedClassesSubjectIdContentIdVideoRoute
}

const AuthenticatedClassesSubjectIdContentIdRouteChildren: AuthenticatedClassesSubjectIdContentIdRouteChildren =
  {
    AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute:
      AuthenticatedClassesSubjectIdContentIdLatihanSoalRoute,
    AuthenticatedClassesSubjectIdContentIdNotesRoute:
      AuthenticatedClassesSubjectIdContentIdNotesRoute,
    AuthenticatedClassesSubjectIdContentIdVideoRoute:
      AuthenticatedClassesSubjectIdContentIdVideoRoute,
  }

const AuthenticatedClassesSubjectIdContentIdRouteWithChildren =
  AuthenticatedClassesSubjectIdContentIdRoute._addFileChildren(
    AuthenticatedClassesSubjectIdContentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedTryoutTryoutIdRoute: typeof AuthenticatedTryoutTryoutIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedTryoutIndexRoute: typeof AuthenticatedTryoutIndexRoute
  AuthenticatedClassesSubjectIdContentIdRoute: typeof AuthenticatedClassesSubjectIdContentIdRouteWithChildren
  AuthenticatedTryoutResultsAttemptIdRoute: typeof AuthenticatedTryoutResultsAttemptIdRoute
  AuthenticatedClassesSubjectIdIndexRoute: typeof AuthenticatedClassesSubjectIdIndexRoute
  AuthenticatedTryoutReviewAttemptIdSubtestIdRoute: typeof AuthenticatedTryoutReviewAttemptIdSubtestIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedTryoutTryoutIdRoute: AuthenticatedTryoutTryoutIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedTryoutIndexRoute: AuthenticatedTryoutIndexRoute,
  AuthenticatedClassesSubjectIdContentIdRoute:
    AuthenticatedClassesSubjectIdContentIdRouteWithChildren,
  AuthenticatedTryoutResultsAttemptIdRoute:
    AuthenticatedTryoutResultsAttemptIdRoute,
  AuthenticatedClassesSubjectIdIndexRoute:
    AuthenticatedClassesSubjectIdIndexRoute,
  AuthenticatedTryoutReviewAttemptIdSubtestIdRoute:
    AuthenticatedTryoutReviewAttemptIdSubtestIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminSuperadminRouteChildren {
  AdminSuperadminProductsProductIdRoute: typeof AdminSuperadminProductsProductIdRoute
  AdminSuperadminProductsCreateRoute: typeof AdminSuperadminProductsCreateRoute
  AdminSuperadminReferralsCodeIdRoute: typeof AdminSuperadminReferralsCodeIdRoute
  AdminSuperadminUsersUserIdRoute: typeof AdminSuperadminUsersUserIdRoute
  AdminSuperadminProductsIndexRoute: typeof AdminSuperadminProductsIndexRoute
  AdminSuperadminReferralsIndexRoute: typeof AdminSuperadminReferralsIndexRoute
  AdminSuperadminUsersIndexRoute: typeof AdminSuperadminUsersIndexRoute
}

const AdminSuperadminRouteChildren: AdminSuperadminRouteChildren = {
  AdminSuperadminProductsProductIdRoute: AdminSuperadminProductsProductIdRoute,
  AdminSuperadminProductsCreateRoute: AdminSuperadminProductsCreateRoute,
  AdminSuperadminReferralsCodeIdRoute: AdminSuperadminReferralsCodeIdRoute,
  AdminSuperadminUsersUserIdRoute: AdminSuperadminUsersUserIdRoute,
  AdminSuperadminProductsIndexRoute: AdminSuperadminProductsIndexRoute,
  AdminSuperadminReferralsIndexRoute: AdminSuperadminReferralsIndexRoute,
  AdminSuperadminUsersIndexRoute: AdminSuperadminUsersIndexRoute,
}

const AdminSuperadminRouteWithChildren = AdminSuperadminRoute._addFileChildren(
  AdminSuperadminRouteChildren,
)

interface AdminClassesSubjectIdContentIdRouteChildren {
  AdminClassesSubjectIdContentIdLatihanSoalRoute: typeof AdminClassesSubjectIdContentIdLatihanSoalRoute
  AdminClassesSubjectIdContentIdNotesRoute: typeof AdminClassesSubjectIdContentIdNotesRoute
  AdminClassesSubjectIdContentIdVideoRoute: typeof AdminClassesSubjectIdContentIdVideoRoute
}

const AdminClassesSubjectIdContentIdRouteChildren: AdminClassesSubjectIdContentIdRouteChildren =
  {
    AdminClassesSubjectIdContentIdLatihanSoalRoute:
      AdminClassesSubjectIdContentIdLatihanSoalRoute,
    AdminClassesSubjectIdContentIdNotesRoute:
      AdminClassesSubjectIdContentIdNotesRoute,
    AdminClassesSubjectIdContentIdVideoRoute:
      AdminClassesSubjectIdContentIdVideoRoute,
  }

const AdminClassesSubjectIdContentIdRouteWithChildren =
  AdminClassesSubjectIdContentIdRoute._addFileChildren(
    AdminClassesSubjectIdContentIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminSuperadminRoute: typeof AdminSuperadminRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPassingGradesUniversityIdRoute: typeof AdminPassingGradesUniversityIdRoute
  AdminQuestionsQuestionIdRoute: typeof AdminQuestionsQuestionIdRoute
  AdminQuestionsCreateRoute: typeof AdminQuestionsCreateRoute
  AdminClassesIndexRoute: typeof AdminClassesIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminPassingGradesIndexRoute: typeof AdminPassingGradesIndexRoute
  AdminQuestionsIndexRoute: typeof AdminQuestionsIndexRoute
  AdminTryoutsIndexRoute: typeof AdminTryoutsIndexRoute
  AdminClassesSubjectIdContentIdRoute: typeof AdminClassesSubjectIdContentIdRouteWithChildren
  AdminClassesSubjectIdIndexRoute: typeof AdminClassesSubjectIdIndexRoute
  AdminTryoutsTryoutIdIndexRoute: typeof AdminTryoutsTryoutIdIndexRoute
  AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute: typeof AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute
  AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute: typeof AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSuperadminRoute: AdminSuperadminRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminPassingGradesUniversityIdRoute: AdminPassingGradesUniversityIdRoute,
  AdminQuestionsQuestionIdRoute: AdminQuestionsQuestionIdRoute,
  AdminQuestionsCreateRoute: AdminQuestionsCreateRoute,
  AdminClassesIndexRoute: AdminClassesIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminPassingGradesIndexRoute: AdminPassingGradesIndexRoute,
  AdminQuestionsIndexRoute: AdminQuestionsIndexRoute,
  AdminTryoutsIndexRoute: AdminTryoutsIndexRoute,
  AdminClassesSubjectIdContentIdRoute:
    AdminClassesSubjectIdContentIdRouteWithChildren,
  AdminClassesSubjectIdIndexRoute: AdminClassesSubjectIdIndexRoute,
  AdminTryoutsTryoutIdIndexRoute: AdminTryoutsTryoutIdIndexRoute,
  AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute:
    AdminTryoutsTryoutIdSubtestsSubtestIdIndexRoute,
  AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute:
    AdminTryoutsTryoutIdSubtestsSubtestIdQuestionsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
